### ISSUE TITLE
STM32L053C and display only works first cycle

### ISSUE THREAD

**Issue by grafisoft** [soonuse/epd-library-stm32#1]
Hi,

i am using the e-papers but i have a problem. When i use the e-paper in first time, all works ok but only work one time. The next cycles the e-paper don´t show anything.

I am using STM32L053C and stm32cubeIDE with HAL.

I think the SPI not works well after first cycle. 

Could you help me?
Thanks,
Regards,

**Comment by Oseihie** [comment]
Hi,
were you able to fix the problem?

**Comment by soonuse** [comment]
Perhaps you didn't set heap size big enough. Try to set the heap size by STM32CubeMx or directly edit the 'startup_stm32fxxxxxx.s' file. See the Heap_Size line.

**Comment by grafisoft** [comment]
Hi,

Yes, i could fix my problem. It was in screen varible declaration, that it was on wrong position, so only works in first cicle.
Thanks for your comments.
REgards,
