### ISSUE TITLE
e-ink 1.54inch B display text

### ISSUE THREAD

**Issue by Oseihie** [soonuse/epd-library-stm32#2]
Hi, I have been able to display images but I have not been able to figure out how to display texts.

I thought the function "Paint_DrawStringAt(&paint_red, 28, 10, "Hello world!", &Font16, UNCOLORED)"
should do that but I am wrong.

Please how do I display texts?

Thank You

Please I really need help with this. Anyone who has displayed texts on an e-paper, your comments will greatly be appreciated.

**Comment by VivLadd8** [comment]
Hello, how did you fix this problem?
